version: "3.9"

services:
  neary:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: neary
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - data_volume:/backend/data

volumes:
  data_volume: